namespace Ascension.Halo_Reach.Game.Misc.Dialogs
{
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;

    public class StingIds : Form
    {
        private ToolStripMenuItem betaMapToolStripMenuItem;
        private Button button1;
        private CheckBox checkBox1;
        private ToolStripMenuItem closeAllToolStripMenuItem;
        private ComboBox comboBox1;
        private ComboBox comboBox2;
        private IContainer components = null;
        private ToolStripMenuItem fileToolStripMenuItem;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private Label label8;
        private MenuStrip menuStrip1;
        private ToolStripMenuItem openToolStripMenuItem;
        private Panel panel1;
        private Panel panel2;
        private Panel panel3;
        private Panel panel4;
        private ToolStripMenuItem retailMapToolStripMenuItem;
        private TextBox textBox1;
        private TextBox textBox2;
        private TextBox textBox3;
        private TextBox textBox4;

        public StingIds()
        {
            InitializeComponent();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            menuStrip1 = new MenuStrip();
            fileToolStripMenuItem = new ToolStripMenuItem();
            openToolStripMenuItem = new ToolStripMenuItem();
            closeAllToolStripMenuItem = new ToolStripMenuItem();
            panel1 = new Panel();
            panel2 = new Panel();
            checkBox1 = new CheckBox();
            label1 = new Label();
            textBox1 = new TextBox();
            label2 = new Label();
            comboBox1 = new ComboBox();
            label3 = new Label();
            textBox2 = new TextBox();
            comboBox2 = new ComboBox();
            label4 = new Label();
            label5 = new Label();
            betaMapToolStripMenuItem = new ToolStripMenuItem();
            retailMapToolStripMenuItem = new ToolStripMenuItem();
            textBox3 = new TextBox();
            panel3 = new Panel();
            panel4 = new Panel();
            label6 = new Label();
            label7 = new Label();
            textBox4 = new TextBox();
            label8 = new Label();
            button1 = new Button();
            menuStrip1.SuspendLayout();
            panel1.SuspendLayout();
            panel2.SuspendLayout();
            panel3.SuspendLayout();
            panel4.SuspendLayout();
            base.SuspendLayout();
            menuStrip1.Items.AddRange(new ToolStripItem[] { fileToolStripMenuItem });
            menuStrip1.Location = new Point(0, 0);
            menuStrip1.Name = "menuStrip1";
            menuStrip1.Size = new Size(0x1f7, 0x18);
            menuStrip1.TabIndex = 0;
            menuStrip1.Text = "menuStrip1";
            fileToolStripMenuItem.DropDownItems.AddRange(new ToolStripItem[] { openToolStripMenuItem, closeAllToolStripMenuItem });
            fileToolStripMenuItem.Name = "fileToolStripMenuItem";
            fileToolStripMenuItem.Size = new Size(0x25, 20);
            fileToolStripMenuItem.Text = "File";
            openToolStripMenuItem.DropDownItems.AddRange(new ToolStripItem[] { betaMapToolStripMenuItem, retailMapToolStripMenuItem });
            openToolStripMenuItem.Name = "openToolStripMenuItem";
            openToolStripMenuItem.Size = new Size(0x98, 0x16);
            openToolStripMenuItem.Text = "Open";
            closeAllToolStripMenuItem.Name = "closeAllToolStripMenuItem";
            closeAllToolStripMenuItem.Size = new Size(0x98, 0x16);
            closeAllToolStripMenuItem.Text = "Close All";
            panel1.BackColor = Color.DarkGray;
            panel1.Controls.Add(panel2);
            panel1.Controls.Add(panel4);
            panel1.Controls.Add(panel3);
            panel1.Location = new Point(9, 0x1b);
            panel1.Name = "panel1";
            panel1.Size = new Size(0x1e2, 0x7b);
            panel1.TabIndex = 1;
            panel2.BackColor = Color.Gray;
            panel2.Controls.Add(comboBox2);
            panel2.Controls.Add(checkBox1);
            panel2.Controls.Add(textBox2);
            panel2.Controls.Add(label4);
            panel2.Controls.Add(label3);
            panel2.Dock = DockStyle.Top;
            panel2.Location = new Point(0, 0);
            panel2.Name = "panel2";
            panel2.Size = new Size(0x1e2, 0x20);
            panel2.TabIndex = 0;
            checkBox1.AutoSize = true;
            checkBox1.Location = new Point(3, 7);
            checkBox1.Name = "checkBox1";
            checkBox1.Size = new Size(60, 0x11);
            checkBox1.TabIndex = 0;
            checkBox1.Text = "Nested";
            checkBox1.UseVisualStyleBackColor = true;
            label1.AutoSize = true;
            label1.Location = new Point(0x31, 8);
            label1.Name = "label1";
            label1.Size = new Size(0x12, 13);
            label1.TabIndex = 1;
            label1.Text = "int";
            textBox1.Location = new Point(0x49, 5);
            textBox1.Name = "textBox1";
            textBox1.Size = new Size(0x37, 20);
            textBox1.TabIndex = 2;
            label2.AutoSize = true;
            label2.Location = new Point(0x86, 8);
            label2.Name = "label2";
            label2.Size = new Size(13, 13);
            label2.TabIndex = 1;
            label2.Text = "+";
            comboBox1.FormattingEnabled = true;
            comboBox1.Location = new Point(0x99, 5);
            comboBox1.Name = "comboBox1";
            comboBox1.Size = new Size(0x42, 0x15);
            comboBox1.TabIndex = 3;
            label3.AutoSize = true;
            label3.Location = new Point(0x4c, 8);
            label3.Name = "label3";
            label3.Size = new Size(0x4d, 13);
            label3.TabIndex = 1;
            label3.Text = "tagblock offset";
            textBox2.Location = new Point(0x9f, 5);
            textBox2.Name = "textBox2";
            textBox2.Size = new Size(0x52, 20);
            textBox2.TabIndex = 2;
            comboBox2.FormattingEnabled = true;
            comboBox2.Location = new Point(0x11e, 5);
            comboBox2.Name = "comboBox2";
            comboBox2.Size = new Size(0x45, 0x15);
            comboBox2.TabIndex = 3;
            label4.AutoSize = true;
            label4.Location = new Point(0xf7, 8);
            label4.Name = "label4";
            label4.Size = new Size(0x21, 13);
            label4.TabIndex = 1;
            label4.Text = "block";
            label5.AutoSize = true;
            label5.Location = new Point(0xe1, 8);
            label5.Name = "label5";
            label5.Size = new Size(13, 13);
            label5.TabIndex = 1;
            label5.Text = "=";
            betaMapToolStripMenuItem.Name = "betaMapToolStripMenuItem";
            betaMapToolStripMenuItem.Size = new Size(0x98, 0x16);
            betaMapToolStripMenuItem.Text = "Beta Map";
            retailMapToolStripMenuItem.Name = "retailMapToolStripMenuItem";
            retailMapToolStripMenuItem.Size = new Size(0x98, 0x16);
            retailMapToolStripMenuItem.Text = "Retail Map";
            textBox3.Location = new Point(0xf4, 5);
            textBox3.Name = "textBox3";
            textBox3.Size = new Size(0x58, 20);
            textBox3.TabIndex = 2;
            panel3.BackColor = Color.Gray;
            panel3.Controls.Add(comboBox1);
            panel3.Controls.Add(textBox3);
            panel3.Controls.Add(label6);
            panel3.Controls.Add(label1);
            panel3.Controls.Add(label2);
            panel3.Controls.Add(textBox1);
            panel3.Controls.Add(label5);
            panel3.Location = new Point(3, 0x2b);
            panel3.Name = "panel3";
            panel3.Size = new Size(0x160, 0x20);
            panel3.TabIndex = 4;
            panel4.BackColor = Color.Gray;
            panel4.Controls.Add(button1);
            panel4.Controls.Add(label7);
            panel4.Controls.Add(textBox4);
            panel4.Controls.Add(label8);
            panel4.Location = new Point(3, 0x51);
            panel4.Name = "panel4";
            panel4.Size = new Size(0x160, 0x20);
            panel4.TabIndex = 4;
            label6.AutoSize = true;
            label6.Location = new Point(3, 8);
            label6.Name = "label6";
            label6.Size = new Size(0x1d, 13);
            label6.TabIndex = 1;
            label6.Text = "Beta";
            label7.AutoSize = true;
            label7.Location = new Point(3, 10);
            label7.Name = "label7";
            label7.Size = new Size(0x22, 13);
            label7.TabIndex = 1;
            label7.Text = "Retail";
            textBox4.Location = new Point(0x49, 7);
            textBox4.Name = "textBox4";
            textBox4.Size = new Size(0x37, 20);
            textBox4.TabIndex = 2;
            label8.AutoSize = true;
            label8.Location = new Point(0x31, 10);
            label8.Name = "label8";
            label8.Size = new Size(0x12, 13);
            label8.TabIndex = 1;
            label8.Text = "int";
            button1.Location = new Point(0x99, 5);
            button1.Name = "button1";
            button1.Size = new Size(0xb3, 0x17);
            button1.TabIndex = 3;
            button1.Text = "Save To List Using Beta SringID";
            button1.UseVisualStyleBackColor = true;
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = AutoScaleMode.Font;
            base.ClientSize = new Size(0x1f7, 0xa5);
            base.Controls.Add(panel1);
            base.Controls.Add(menuStrip1);
            base.MainMenuStrip = menuStrip1;
            base.Name = "StingIds";
            Text = "StingIds";
            menuStrip1.ResumeLayout(false);
            menuStrip1.PerformLayout();
            panel1.ResumeLayout(false);
            panel2.ResumeLayout(false);
            panel2.PerformLayout();
            panel3.ResumeLayout(false);
            panel3.PerformLayout();
            panel4.ResumeLayout(false);
            panel4.PerformLayout();
            base.ResumeLayout(false);
            base.PerformLayout();
        }
    }
}

